apiVersion: v1
kind: Service
metadata:
  name: fitness-server-backend-service
spec:
  selector:
    app: fitness-server-backend
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: LoadBalancer
