apiVersion: v1
kind: Service
metadata:
  name: fitness-client-frontend-service
spec:
  selector:
    app: fitness-client-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
